hydra:
    run:
        dir: /kqi/output/fold_${dataset.target_fold}
    sweep:
        dir: /kqi/output
        subdir: ${hydra.job.num}

model:
    class_name: segmentation_models_pytorch.Unet
    params: {encoder_name: efficientnet-b3, in_channels: 3, classes: 1}

dataset:
    cv_split:
        class_name: sklearn.model_selection.KFold
        params: {n_splits: 4, shuffle: false}

training:
    scheduler:
        class_name: torch.optim.lr_scheduler.CosineAnnealingLR
        params: {T_max: 100}
    #loss:
    #    class_name: loss.boundary_loss.DC_and_HDBinary_loss
    #    params: {soft_dice_kwargs: {}, hd_kwargs: {}}